//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTC.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProjectTCResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectTCResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectTC.Resx.ProjectTCResx", typeof(ProjectTCResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 추가.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 첨부파일.
        /// </summary>
        public static string AttachFile {
            get {
                return ResourceManager.GetString("AttachFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 하.
        /// </summary>
        public static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 현재버그.
        /// </summary>
        public static string CurrentBug {
            get {
                return ResourceManager.GetString("CurrentBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 삭제.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 기대효과.
        /// </summary>
        public static string ExpectResult {
            get {
                return ResourceManager.GetString("ExpectResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        public static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 필터.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 상.
        /// </summary>
        public static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 중.
        /// </summary>
        public static string Middle {
            get {
                return ResourceManager.GetString("Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        public static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 환경세팅.
        /// </summary>
        public static string PreCondition {
            get {
                return ResourceManager.GetString("PreCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 프로그램버전.
        /// </summary>
        public static string ProgramVersion {
            get {
                return ResourceManager.GetString("ProgramVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 프로젝트명.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 결과.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 순번.
        /// </summary>
        public static string Seq {
            get {
                return ResourceManager.GetString("Seq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 탭복사.
        /// </summary>
        public static string TabCopy {
            get {
                return ResourceManager.GetString("TabCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 테스트명.
        /// </summary>
        public static string TestName {
            get {
                return ResourceManager.GetString("TestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 재현경로.
        /// </summary>
        public static string TestStep {
            get {
                return ResourceManager.GetString("TestStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 총합.
        /// </summary>
        public static string TotCnt {
            get {
                return ResourceManager.GetString("TotCnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 총 미완료.
        /// </summary>
        public static string TotNoCnt {
            get {
                return ResourceManager.GetString("TotNoCnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 총 완료.
        /// </summary>
        public static string TotYesCnt {
            get {
                return ResourceManager.GetString("TotYesCnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 프로그램버전.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
